name: Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  Build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v2

    - name: Configurar entorno
      run: |
        cd cliente/
        npm install
        CI='' npm run build

    - name: Ejecutar pruebas unitarias
      run: |
        cd cliente/ 
        npm test
    
