name: Workflow de prueba unitaria

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v2

    - name: Configurar entorno
      run: |
        cd cliente
        npm install
        npm run build
  Test:
    need: Build
    runs-on: ubuntu-latest

    steps:
    - name: Ejecutar pruebas unitarias
      run: npm test
